#!/usr/bin/env node
// Fork Cleanup Analyzer — finds owned forks that aren't serving an active PR purpose,
// and suggests which can be deleted or made private to clean up the profile.
//
// SAFETY: This script NEVER deletes anything. It only generates a report
// for manual review. The user runs the actual `gh repo delete` or `gh repo edit --visibility private`
// commands themselves after reviewing.

import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const USER = process.env.GH_USER || 'theihtisham';
const REPORT_PATH = 'docs/FORK_CLEANUP_REPORT.md';

function gh(cmd, fallback = null) {
  try { return JSON.parse(execSync(`gh ${cmd}`, { encoding: 'utf-8' })); }
  catch { return fallback; }
}

console.log(`Analyzing forks owned by ${USER}...`);

// 1. List all forks owned by the user
const repos = gh(`repo list ${USER} --limit 200 --fork --json name,nameWithOwner,parent,isPrivate,isArchived,stargazerCount,forkCount,updatedAt,description`) || [];
console.log(`Found ${repos.length} forks.`);

// 2. For each fork, check if there's a PR to upstream
const analyzed = [];
for (const r of repos) {
  if (!r.parent) continue;

  const parentName = r.parent.nameWithOwner;
  const upstreamPRs = gh(`pr list --repo ${parentName} --author ${USER} --state all --json number,state,title,url --limit 5`) || [];

  const hasOpenPR = upstreamPRs.some(p => p.state === 'OPEN');
  const hasMergedPR = upstreamPRs.some(p => p.state === 'MERGED');
  const hasClosedPR = upstreamPRs.some(p => p.state === 'CLOSED' && !hasMergedPR);

  let recommendation = 'KEEP';
  let reason = '';

  if (hasOpenPR) {
    recommendation = 'KEEP';
    reason = 'Open PR to upstream depends on this fork';
  } else if (hasMergedPR) {
    recommendation = 'PRIVATE';
    reason = 'PR was merged — fork no longer needed but useful for history';
  } else if (hasClosedPR) {
    recommendation = 'DELETE';
    reason = 'PR was closed (rejected) — fork no longer serving a purpose';
  } else if (r.stargazerCount === 0 && r.forkCount === 0) {
    recommendation = 'DELETE';
    reason = 'No PRs to upstream, no stars, no forks — looks like an unused fork';
  } else {
    recommendation = 'PRIVATE';
    reason = 'No PR activity but fork has some signals — privatize to declutter profile';
  }

  analyzed.push({
    name: r.name,
    parent: parentName,
    private: r.isPrivate,
    archived: r.isArchived,
    stars: r.stargazerCount,
    forks: r.forkCount,
    updated: r.updatedAt,
    upstreamPRs: upstreamPRs.length,
    hasOpenPR,
    hasMergedPR,
    hasClosedPR,
    recommendation,
    reason,
  });

  // Be polite to the API
  await new Promise(r => setTimeout(r, 100));
}

const toDelete = analyzed.filter(a => a.recommendation === 'DELETE' && !a.private);
const toPrivate = analyzed.filter(a => a.recommendation === 'PRIVATE' && !a.private);
const toKeep = analyzed.filter(a => a.recommendation === 'KEEP');

const md = `# Fork Cleanup Report

_Auto-generated by the Viral Amplifier Bot. Last refresh: ${new Date().toISOString().slice(0, 10)}._

**User:** [${USER}](https://github.com/${USER})

## Summary

| Recommendation | Count |
|---|---:|
| 🟢 KEEP (active PR) | ${toKeep.length} |
| 🟡 PRIVATE (declutter profile) | ${toPrivate.length} |
| 🔴 DELETE (no purpose) | ${toDelete.length} |
| **Total forks analyzed** | ${analyzed.length} |

> ⚠️ This script NEVER deletes or modifies anything. All actions below require your manual review and approval.

---

## 🔴 Forks to Consider Deleting (${toDelete.length})

These forks have no open or merged PR to upstream and minimal activity. Likely safe to delete.

${toDelete.length === 0 ? '_None._' : ''}
${toDelete.map(a => `### [${USER}/${a.name}](https://github.com/${USER}/${a.name})

- **Upstream:** [${a.parent}](https://github.com/${a.parent})
- **Reason:** ${a.reason}
- **Last updated:** ${a.updated}
- **Stars on fork:** ${a.stars}, **Forks of fork:** ${a.forks}

\`\`\`bash
gh repo delete ${USER}/${a.name} --yes
\`\`\`
`).join('\n')}

---

## 🟡 Forks to Consider Making Private (${toPrivate.length})

These forks served their purpose (PR was merged or has activity) but clog the public profile. Privatizing keeps history but removes from your profile listing.

${toPrivate.length === 0 ? '_None._' : ''}
${toPrivate.map(a => `### [${USER}/${a.name}](https://github.com/${USER}/${a.name})

- **Upstream:** [${a.parent}](https://github.com/${a.parent})
- **Reason:** ${a.reason}
- **Upstream PRs:** ${a.upstreamPRs} (merged: ${a.hasMergedPR ? 'yes' : 'no'})

\`\`\`bash
gh repo edit ${USER}/${a.name} --visibility private --accept-visibility-change-consequences
\`\`\`
`).join('\n')}

---

## 🟢 Forks to Keep (${toKeep.length})

These forks have an OPEN PR to upstream — deleting them would close the PR.

${toKeep.length === 0 ? '_None._' : ''}
${toKeep.map(a => `- [${USER}/${a.name}](https://github.com/${USER}/${a.name}) → [${a.parent}](https://github.com/${a.parent}) — ${a.upstreamPRs} PR(s)`).join('\n')}

---

## Bulk Cleanup Commands (review carefully before running!)

To delete all "DELETE" candidates in one command:

\`\`\`bash
${toDelete.map(a => `gh repo delete ${USER}/${a.name} --yes`).join('\n')}
\`\`\`

To privatize all "PRIVATE" candidates:

\`\`\`bash
${toPrivate.map(a => `gh repo edit ${USER}/${a.name} --visibility private --accept-visibility-change-consequences`).join('\n')}
\`\`\`

---

## How This Was Determined

For each fork:
1. Look up the upstream parent repo (\`fork.parent\`)
2. Query upstream for PRs authored by you (\`gh pr list --repo PARENT --author YOU\`)
3. Apply rules:
   - Open PR exists → **KEEP**
   - Merged PR exists → **PRIVATE** (history valuable, profile clutter)
   - Only closed (rejected) PRs → **DELETE**
   - No PRs + 0 stars + 0 forks → **DELETE**
   - No PRs but some signals → **PRIVATE**

If the script flagged something incorrectly, just keep it. The recommendations are conservative — when in doubt, KEEP.

## Re-Run

\`\`\`bash
node .github/scripts/fork-cleanup.mjs
\`\`\`

The script is read-only — safe to run anytime.
`;

mkdirSync(dirname(REPORT_PATH), { recursive: true });
writeFileSync(REPORT_PATH, md);
console.log(`Fork cleanup report: ${toDelete.length} delete, ${toPrivate.length} private, ${toKeep.length} keep.`);
console.log(`Report at ${REPORT_PATH}`);
