#!/usr/bin/env node
// Inclusion Checker — searches awesome-* repos for the project URL to find which lists already include it.
// Saves time by not submitting to lists that already have it.
// Uses GitHub code search — strictly read-only, no PRs created here.

import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const REPO = process.env.REPO || 'theihtisham/agent-shadow-brain';
const PROJECT_URL = `github.com/${REPO}`;
const PKG_NAME = '@theihtisham/agent-shadow-brain';
const REPORT_PATH = 'docs/INCLUSION_REPORT.md';

function ghSearchCode(q, limit = 30) {
  try {
    return JSON.parse(execSync(`gh api -X GET 'search/code?q=${encodeURIComponent(q)}&per_page=${limit}' --jq '.items'`, { encoding: 'utf-8' }));
  } catch { return []; }
}

console.log('Searching for inclusion in awesome-* lists...');

// Two queries — we cast a wide net then filter
const q1 = `"${PROJECT_URL}" in:file extension:md`;
const q2 = `"${PKG_NAME}" in:file extension:md`;

const r1 = ghSearchCode(q1, 30);
const r2 = ghSearchCode(q2, 30);

const all = [...r1, ...r2];
const seen = new Set();
const inclusions = [];

for (const item of all) {
  const repo = item.repository?.full_name;
  const path = item.path;
  if (!repo || seen.has(repo + path)) continue;
  seen.add(repo + path);

  // Filter: only count repos with "awesome" in name (probably an awesome list)
  const isAwesomeList = /awesome/i.test(repo) || /awesome/i.test(path);
  if (!isAwesomeList) continue;

  inclusions.push({
    repo,
    path,
    url: item.html_url,
    repo_url: `https://github.com/${repo}`,
  });
}

const md = `# Inclusion Report — Awesome Lists

_Auto-generated by the Viral Amplifier Bot. Last refresh: ${new Date().toISOString().slice(0, 10)}._

**Project:** [${REPO}](https://github.com/${REPO})
**Package:** \`${PKG_NAME}\`

## Lists That Already Include This Project: **${inclusions.length}**

${inclusions.length === 0 ? '_None found yet. See `docs/awesome-list-targets.md` for candidate lists to submit to._' : inclusions.map(i => `- [${i.repo}](${i.repo_url}) → [${i.path}](${i.url})`).join('\n')}

---

## How to Use This Report

- ✅ Lists below are **already including** the project. Don't re-submit.
- 📤 To find lists to submit to, see [\`docs/awesome-list-targets.md\`](./awesome-list-targets.md).
- 🔁 This report refreshes when the workflow runs. Check before any submission to avoid duplicates.

## Search Methodology

This report uses GitHub Code Search to find any markdown file in any public repo that mentions:
1. The project's GitHub URL
2. The project's npm package name

It then filters to only repos that contain "awesome" in their name or path. False positives possible — review before relying on the list.

GitHub Code Search has rate limits (30 req/min for unauthenticated). Authenticated runs (with \`GH_TOKEN\` set, which the workflow does) get 5000 req/hour.
`;

mkdirSync(dirname(REPORT_PATH), { recursive: true });
writeFileSync(REPORT_PATH, md);
console.log(`Inclusion report: ${inclusions.length} awesome lists found.`);
