#!/usr/bin/env python3
"""serve_lora.py — Serve a trained LoRA adapter.

Two modes:

  1. FastAPI HTTP server (default)
       python serve_lora.py --adapter ./demo/lora-adapter --port 8765
       curl -X POST http://127.0.0.1:8765/chat \\
            -H "Content-Type: application/json" \\
            -d '{"messages":[{"role":"user","content":"What is our password hashing policy?"}]}'

  2. GGUF conversion + Ollama Modelfile (for `ollama create`)
       python serve_lora.py --adapter ./demo/lora-adapter --gguf --output ./demo/lora-adapter

Required pip install (BEFORE running):
  pip install fastapi uvicorn transformers peft torch  # for FastAPI mode

Why each dep:
  fastapi        — small HTTP server
  uvicorn        — ASGI server
  transformers   — base model
  peft           — load LoRA adapter
  torch          — runtime

GGUF mode also requires llama.cpp's convert.py and quantize binaries on PATH.
This script does NOT download or build llama.cpp — it only writes the Modelfile
template and prints the exact commands the user must run.

Usage:
  python serve_lora.py --adapter ./demo/lora-adapter --port 8765
  python serve_lora.py --adapter ./demo/lora-adapter --gguf
  python serve_lora.py --adapter ./demo/lora-adapter --dry-run
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


# ----------------------------------------------------------------------------
# Ollama Modelfile template
# ----------------------------------------------------------------------------

MODELFILE_TEMPLATE = """# Ollama Modelfile generated by shadow-brain LoRA pipeline.
# Build with: ollama create my-project-brain -f Modelfile
FROM ./model.gguf

TEMPLATE \"\"\"{{- if .System -}}<|im_start|>system
{{ .System }}<|im_end|>
{{ end -}}
{{- range .Messages -}}
<|im_start|>{{ .Role }}
{{ .Content }}<|im_end|>
{{ end -}}
<|im_start|>assistant
\"\"\"

PARAMETER stop "<|im_end|>"
PARAMETER stop "<|im_start|>"
PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER num_ctx 4096

SYSTEM \"\"\"You are an AI engineer assistant for this codebase. Use the team's
established conventions, decisions, and patterns. Be concise and specific.\"\"\"
"""


# ----------------------------------------------------------------------------
# DEP CHECK
# ----------------------------------------------------------------------------

def check_dependencies(mode: str) -> list[str]:
    import importlib.util
    needed = ["torch", "transformers", "peft"]
    if mode == "fastapi":
        needed += ["fastapi", "uvicorn"]
    return [n for n in needed if importlib.util.find_spec(n) is None]


def fail_missing(missing: list[str], mode: str) -> None:
    print(f"\nERROR: missing required deps for {mode} mode: {missing}", file=sys.stderr)
    if mode == "fastapi":
        print("\n  pip install fastapi uvicorn transformers peft torch", file=sys.stderr)
    else:
        print("\n  pip install transformers peft torch", file=sys.stderr)
    sys.exit(3)


# ----------------------------------------------------------------------------
# FastAPI mode
# ----------------------------------------------------------------------------

def run_fastapi(args: argparse.Namespace) -> int:
    missing = check_dependencies("fastapi")
    if missing:
        fail_missing(missing, "fastapi")

    import torch
    from fastapi import FastAPI
    from pydantic import BaseModel
    from transformers import AutoTokenizer, AutoModelForCausalLM
    from peft import PeftModel
    import uvicorn

    info_path = args.adapter / "training-info.json"
    base_model_id = args.base_model
    if info_path.exists():
        try:
            base_model_id = json.loads(info_path.read_text(encoding="utf-8")).get("base_model", base_model_id)
        except json.JSONDecodeError:
            pass

    print(f"  loading base model: {base_model_id}")
    tokenizer = AutoTokenizer.from_pretrained(base_model_id)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    base = AutoModelForCausalLM.from_pretrained(base_model_id, torch_dtype="auto", device_map="auto")
    print(f"  loading adapter: {args.adapter}")
    model = PeftModel.from_pretrained(base, str(args.adapter))
    model.eval()

    class Message(BaseModel):
        role: str
        content: str

    class ChatRequest(BaseModel):
        messages: list[Message]
        max_tokens: int = 256
        temperature: float = 0.2

    app = FastAPI(title="shadow-brain LoRA")

    @app.get("/health")
    def health() -> dict[str, str]:
        return {"status": "ok", "base_model": base_model_id, "adapter": str(args.adapter)}

    @app.post("/chat")
    def chat(req: ChatRequest) -> dict[str, str]:
        # Ensure a system prompt
        msgs = [m.model_dump() for m in req.messages]
        if not any(m["role"] == "system" for m in msgs):
            msgs = [{
                "role": "system",
                "content": "You are an AI engineer assistant for this codebase. Be concise and specific.",
            }] + msgs
        prompt = tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        with torch.no_grad():
            out = model.generate(
                **inputs,
                max_new_tokens=req.max_tokens,
                temperature=req.temperature,
                do_sample=req.temperature > 0,
                pad_token_id=tokenizer.eos_token_id,
            )
        text = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
        return {"reply": text.strip()}

    print(f"  serving on http://{args.host}:{args.port}")
    uvicorn.run(app, host=args.host, port=args.port, log_level="info")
    return 0


# ----------------------------------------------------------------------------
# GGUF mode (stub — writes commands the user must run with llama.cpp)
# ----------------------------------------------------------------------------

def write_gguf_stub(args: argparse.Namespace) -> int:
    out_dir = args.output or args.adapter
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write the Modelfile template
    modelfile_path = out_dir / "Modelfile"
    modelfile_path.write_text(MODELFILE_TEMPLATE, encoding="utf-8")
    print(f"  wrote {modelfile_path}")

    # Write a convert.sh script the user can run with llama.cpp
    convert_script = out_dir / "convert-to-gguf.sh"
    convert_script.write_text(f"""#!/usr/bin/env bash
# convert-to-gguf.sh — merge LoRA into base, then convert to GGUF for Ollama.
# Requires llama.cpp checked out somewhere (LLAMACPP env var).
set -euo pipefail

ADAPTER="{args.adapter}"
BASE_MODEL="{args.base_model}"
LLAMACPP="${{LLAMACPP:-$HOME/code/llama.cpp}}"
OUT_DIR="{out_dir}"

# 1. Merge LoRA into base weights (requires peft)
python - <<'PY'
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel
import os
adapter = os.environ.get("ADAPTER", "{args.adapter}")
base = os.environ.get("BASE_MODEL", "{args.base_model}")
out = os.environ.get("OUT_DIR", "{out_dir}")
print(f"merging {{adapter}} into {{base}}...")
tok = AutoTokenizer.from_pretrained(base)
mdl = AutoModelForCausalLM.from_pretrained(base, torch_dtype="auto")
mdl = PeftModel.from_pretrained(mdl, adapter)
mdl = mdl.merge_and_unload()
mdl.save_pretrained(f"{{out}}/merged")
tok.save_pretrained(f"{{out}}/merged")
print("merged.")
PY

# 2. Convert merged HF model to GGUF
python "$LLAMACPP/convert.py" "$OUT_DIR/merged" --outtype f16 --outfile "$OUT_DIR/model.gguf"

# 3. Optional: quantize to Q4_K_M (smaller, faster)
"$LLAMACPP/quantize" "$OUT_DIR/model.gguf" "$OUT_DIR/model-q4.gguf" Q4_K_M || true

# 4. Build the Ollama model
cd "$OUT_DIR"
ollama create my-project-brain -f Modelfile
echo "Run with: ollama run my-project-brain"
""", encoding="utf-8")
    try:
        convert_script.chmod(0o755)
    except OSError:
        pass
    print(f"  wrote {convert_script}")

    print("\n  Next steps:")
    print(f"    1. Install llama.cpp: git clone https://github.com/ggerganov/llama.cpp")
    print(f"    2. export LLAMACPP=/path/to/llama.cpp")
    print(f"    3. bash {convert_script}")
    print(f"    4. ollama run my-project-brain")
    return 0


# ----------------------------------------------------------------------------
# DRY RUN
# ----------------------------------------------------------------------------

def dry_run(args: argparse.Namespace) -> int:
    print("\n=== DRY RUN ===")
    print(f"  adapter:   {args.adapter}")
    print(f"  base:      {args.base_model}")
    if args.gguf:
        print("  mode:      gguf-conversion (writes Modelfile + convert script)")
        print(f"  output:    {args.output or args.adapter}")
    else:
        print("  mode:      fastapi")
        print(f"  host:port: {args.host}:{args.port}")

    mode = "fastapi" if not args.gguf else "merge"
    missing = check_dependencies(mode if mode == "fastapi" else "merge-base")
    if missing:
        print(f"  MISSING deps: {missing}")
    print("\n  --dry-run set; not loading any model or serving.")
    return 0


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Serve the trained LoRA adapter via FastAPI or convert for Ollama.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--adapter", type=Path, required=True, help="Path to the trained LoRA adapter")
    p.add_argument("--base-model", type=str, default="unsloth/Qwen2.5-Coder-1.5B-Instruct")
    p.add_argument("--port", type=int, default=8765)
    p.add_argument("--host", type=str, default="127.0.0.1")
    p.add_argument("--gguf", action="store_true", help="Write GGUF conversion + Ollama Modelfile stub")
    p.add_argument("--output", type=Path, default=None, help="(GGUF mode only) output dir for Modelfile + script")
    p.add_argument("--dry-run", action="store_true")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.dry_run:
        return dry_run(args)
    if not args.adapter.exists():
        print(f"ERROR: adapter not found: {args.adapter}", file=sys.stderr)
        return 2
    if args.gguf:
        return write_gguf_stub(args)
    return run_fastapi(args)


if __name__ == "__main__":
    raise SystemExit(main())
