// src/adapters/base-adapter.ts — Base class for all agent adapters

import * as fs from 'fs';
import * as path from 'path';
import { AgentAdapter, AgentMemory, AgentActivity, AgentPaths, AgentTool, BrainInsight } from '../types.js';

export abstract class BaseAdapter implements AgentAdapter {
  abstract name: AgentTool;
  abstract displayName: string;

  protected projectDir: string = '';

  abstract detect(): Promise<boolean>;
  abstract getConfigPaths(): AgentPaths;
  abstract readActivity(): Promise<AgentActivity[]>;

  async getProjectDir(): Promise<string | null> {
    return this.projectDir || null;
  }

  setProjectDir(dir: string): void {
    this.projectDir = dir;
  }

  async readMemory(): Promise<AgentMemory> {
    const paths = this.getConfigPaths();
    const memory: AgentMemory = {
      rules: [],
      context: [],
      recentFiles: [],
      projectKnowledge: {},
    };

    // Read rules/instructions files
    if (fs.existsSync(paths.rulesDir)) {
      const files = fs.readdirSync(paths.rulesDir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        try {
          const content = fs.readFileSync(path.join(paths.rulesDir, file), 'utf-8');
          memory.rules.push(content);
        } catch { /* skip */ }
      }
    }

    // Read memory files
    if (fs.existsSync(paths.memoryDir)) {
      const files = fs.readdirSync(paths.memoryDir).filter(f => f.endsWith('.md') || f.endsWith('.json'));
      for (const file of files) {
        try {
          const content = fs.readFileSync(path.join(paths.memoryDir, file), 'utf-8');
          memory.projectKnowledge[file] = content;
        } catch { /* skip */ }
      }
    }

    return memory;
  }

  async injectContext(insight: BrainInsight): Promise<boolean> {
    const paths = this.getConfigPaths();
    const injectionDir = path.join(paths.memoryDir, 'shadow-brain');

    try {
      fs.mkdirSync(injectionDir, { recursive: true });

      const filename = `${insight.priority}-${insight.type}-${Date.now()}.md`;
      const content = this.formatInsight(insight);

      fs.writeFileSync(path.join(injectionDir, filename), content, 'utf-8');

      // Also update the main brain file
      const brainFile = path.join(injectionDir, 'BRAIN.md');
      const existing = fs.existsSync(brainFile) ? fs.readFileSync(brainFile, 'utf-8') : '';
      const updated = this.appendToBrainFile(existing, insight);
      fs.writeFileSync(brainFile, updated, 'utf-8');

      return true;
    } catch {
      return false;
    }
  }

  protected formatInsight(insight: BrainInsight): string {
    const priorityEmoji: Record<string, string> = {
      critical: '🚨',
      high: '⚠️',
      medium: '💡',
      low: 'ℹ️',
    };

    return `# ${priorityEmoji[insight.priority]} ${insight.title}

**Type:** ${insight.type} | **Priority:** ${insight.priority}
**Time:** ${insight.timestamp.toISOString()}
${insight.files?.length ? `**Files:** ${insight.files.join(', ')}` : ''}

---

${insight.content}
`;
  }

  protected appendToBrainFile(existing: string, insight: BrainInsight): string {
    const header = existing
      ? existing.split('\n---\n')[0] + '\n'
      : `# 🧠 Shadow Brain Insights\n\n_Auto-generated by agent-shadow-brain. These are real-time reviews and suggestions._\n\n`;

    // Keep last 20 insights max
    const sections = existing.split('\n---\n').filter(s => s.trim());
    const insights = sections.slice(1).slice(-19); // keep 19 + new one = 20

    const newEntry = `
## ${insight.priority === 'critical' ? '🚨' : insight.priority === 'high' ? '⚠️' : '💡'} [${insight.type.toUpperCase()}] ${insight.title}
_${insight.timestamp.toISOString()}_

${insight.content}
${insight.files?.length ? `\nFiles: \`${insight.files.join('`, `')}\`` : ''}`;

    return header + '\n---\n' + [...insights, newEntry].join('\n---\n') + '\n';
  }

  protected fileExists(filePath: string): boolean {
    return fs.existsSync(filePath);
  }

  protected readFile(filePath: string): string | null {
    try {
      return fs.readFileSync(filePath, 'utf-8');
    } catch {
      return null;
    }
  }
}
